# Версия docker-compose
version: '3.2'
# Список наших сервисов (контейнеров)

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  redis-data:
  pg-data:
  home-dir:

services:
  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  composer:
    image: composer:1.6
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install

  postgres:
    image: postgres:9.6.10-alpine
    restart: always
    environment:
      POSTGRES_DB: pg-db-name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    ports:
      - 15432:5432 # Port 15432 for connecting from localhost using, for example, data-grip

  redis:
    image: redis:4.0.11-alpine
    restart: always
    command: redis-server
    volumes:
      - redis-data:/data:rw
    ports:
      - 16379:6379 # Port 16379 for connecting from localhost
    networks:
      - backend-network

